export const NotificationError = {
  GENERAL_ERROR: 'Ha sucedido un error inesperado, no se ha podido conectar con el servicio',
  GET_TASKS_ERROR: 'Ha ocurrido un problema al obtener las tareas',
  VALIDATION_TASK_ERROR: 'Error de validaci√≥n, por favor revise los campos',
  TASK_ERROR: 'Ha ocurrido un error inesperado, espere un momento',
  FORM_VALIDATION_ERROR: 'Hubo un error, por favor revise los campos'
}